resolutions/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :goals
  resources :users
  resource :session

end

resolutions/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id           :integer          not null, primary key
#  body         :string(255)      not null
#  sayable_id   :integer          not null
#  sayable_type :string(255)      not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Comment < ActiveRecord::Base

  belongs_to :sayable, polymorphic: true

end

resolutions/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  user_id    :integer          not null
#  access     :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Goal < ActiveRecord::Base
  has_many :comments, as: :sayable
end

resolutions/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password

  before_validation :ensure_session_token
  validates :username, presence: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }, on: :create


  has_many :comments, as: :sayable

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def password=(plain_text)
    @password = plain_text
    self.password_digest = BCrypt::Password.create(plain_text) unless plain_text.empty?
  end

  def is_password?(plain_text)
    BCrypt::Password.new(self.password_digest).is_password?(plain_text)
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.hex
  end
end

resolutions/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    user.session_token = SecureRandom.hex
    user.save!
    session[:session_token] = user.session_token
  end

  def logout
    current_user.session_token = SecureRandom.hex
    session[:session_token] = nil
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

resolutions/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      if comment_params[:sayable_type]=="User"
        redirect_to user_url(comment_params[:sayable_id])
      elsif comment_params[:sayable_type]=="Goal"
        redirect_to goal_url(comment_params[:sayable_id])
      end
    else
      flash[:error] = "Andrew sucks"
      redirect_to user_url(comment_params[:sayable_id])
    end
  end

  def comment_params
    params.require(:comment).permit(:body, :sayable_type, :sayable_id)
  end
end

resolutions/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @goal= Goal.find(params[:id])
    @comments = @goal.comments
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id

    respond_to do |format|
      if @goal.save
        format.html { redirect_to goals_url, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to goals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:title, :user_id, :access)
    end
end

resolutions/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      login(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = ["You fucked up son"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

resolutions/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @comments = @user.comments
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :session_token)
  end
end

resolutions/app/helpers/application_helper.rb
module ApplicationHelper
end

resolutions/app/helpers/comments_helper.rb
module CommentsHelper
end

resolutions/app/helpers/goals_helper.rb
module GoalsHelper
end

resolutions/app/helpers/sessions_helper.rb
module SessionsHelper
end

resolutions/app/helpers/users_helper.rb
module UsersHelper
end

resolutions/app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label>Public<br>
      <%= f.radio_button(:access, "public") %>
    </label>
  </div>

  <div class="field">
    <label>Private<br>
      <%= f.radio_button(:access, "private") %>
    </label>
  </div>

  <div class="actions">
    <%if controller.action_name == 'edit'%>
      <%= f.submit("Edit Goal") %>
    <%else%>
      <%= f.submit("Make New Goal") %>
    <%end%>
  </div>
<% end %>

resolutions/app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

resolutions/app/views/goals/index.html.erb
<h1>Listing goals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Access</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>

        <%= goal.access%>
        <%= goal.user_id%>
        <%= current_user.id%>

        <% if goal.access =='public' || goal.user_id.to_i == current_user.id.to_i%>


        <td><%= goal.title %></td>
        <td><%= goal.user_id %></td>
        <td><%= goal.access %></td>
        <td><%= link_to goal.title, goal_url(goal) %></td>
        <td><%= button_to 'Edit', edit_goal_url(goal) %></td>
        <td><%= button_to 'Delete', goal_url(goal.id), method: :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Goal', new_goal_path %>

resolutions/app/views/goals/new.html.erb
<h1>Create New Goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

resolutions/app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @goal.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @goal.user_id %>
</p>

<p>
  <strong>Access:</strong>
  <%= @goal.access %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>


<%@comments.each do |comment|%>
  <br><%=comment.body%>
<%end%>
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[sayable_type]" value="Goal">
  <input type="hidden" name="comment[sayable_id]" value="<%= @goal.id %>">
  <label>Body<br>
    <input type="text", name="comment[body]">
  </label>
  <br>
  <input type="submit" value="Add Comment">
</form>

resolutions/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goals App</title>
</head>
<body>
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<%= link_to "Sign Up", new_user_url%>
<%= link_to "Sign In", new_session_url%>
<%= link_to "Goals", goals_url%>

<% if logged_in? %>
  Logged in as <%= link_to current_user.username, user_url(current_user.id) %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% end %>

<%= yield %>

</body>
</html>

resolutions/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label> Username<br>
    <input type="text" name="user[username]">
  </label>
  <br>
  <label> Password<br>
    <input type="text" name="user[password]">
  </label>
  <br>
  <input type="submit" value="Sign Up">
</form>

resolutions/app/views/users/show.html.erb
<h1>Show page for <%= @user.username %></h1>

<%@comments.each do |comment|%>
  <br><%=comment.body%>
<%end%>
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[sayable_type]" value="User">
  <input type="hidden" name="comment[sayable_id]" value="<%= @user.id %>">
  <label>Body<br>
    <input type="text", name="comment[body]">
  </label>
  <br>
  <input type="submit" value="Add Comment">
</form>